### ISSUE TITLE
Version 8.0 broke predefined user snippets

### ISSUE THREAD

**Issue by Bacco** [APerricone/harbourCodeExtension#10]
Since 8.0 version (tested with 8.1.0 and 8.2.0 too) I can't use my predefined code snippets for harbour (not ones bundled with the extension). After some huge slowdown, I receive this error:

> [Error - 10:55:44 AM] Request textDocument/completion failed.
>   Message: Request textDocument/completion failed with message: Invalid string length
>   Code: -32603

Also, code starts to consume fully a CPU core for a while. 

![screenshot of the error message](https://user-images.githubusercontent.com/3887956/51182120-44dc9f00-18b4-11e9-8262-73ee70b1b439.png)

Reverting to 7.9 clears the issue and my snippets start to behave normally, probably it's a conflict with extension provided and user provided snippets.

Here, my snippets file, just in case:

`harbour.json`

```
{
	"Console Main": {
		"scope": "harbour",
		"prefix": "main",
		"body": [
			"//Basic Console App 3.0.1",
			"",
			"#require \"b2\"",
			"",
			"",
			"Procedure Main()",
			"\tExternal HB_CODEPAGE_PTISO",
			"\thb_cdpSelect( 'PTISO' )",
			"\tSet( _SET_DATEFORMAT, 'dd/mm/yyyy' )",
			"\tSet( _SET_EXACT, .t. )",
			"",
			"\t$1",
			"",
			"\tReturn",
			"",
			"",
			""
		]
	},
	"Qt Main": {
		"scope": "harbour",
		"prefix": "qtmain",
		"body": [
			"//Basic Qt App 3.0.1",
			"",
			"#require \"b2\"",
			"#require \"hbqt\"",
			"",
			"",
			"Procedure Main()",
			"Local oWid",
			"",
			"\tExternal HB_CODEPAGE_PTISO",
			"\thb_cdpSelect( 'PTISO' )",
			"\tSet( _SET_DATEFORMAT, 'dd/mm/yyyy' )",
			"\tSet( _SET_EXACT, .t. )",
			"",
			"\toWid := QWidget()",
			"\t//oWid:setWindowTitle( ' ' )",
			"",
			"\t$1",
			"",
			"\t//oLay1 := QVBoxLayout( oWid )",
			"\t//oLay1:addWidget(  )",
			"",
			"\toWid:show()",
			"\tQApplication():exec()",
			"",
			"\tReturn",
			"",
			"",
			""
		]
	},
	"#pragma BEGINDUMP": {
		"scope": "harbour",
		"prefix": "dump",
		"body": [
			"#pragma BEGINDUMP",
			"",
			"",
			"#include \"hbapi.h\"",
			"//#include \"hbapierr.h\"",
			"",
			"HB_FUNC( $1 )",
			"{",
			"\t$2",
			"}",
			"",
			"",
			"",
			"#pragma ENDDUMP",
			"",
			"",
			""
		]
	}
}

```

**Comment by APerricone** [comment]
Hi, 
Thank you for report,
how much is big the file you editing?

**Comment by APerricone** [comment]
Thank you for your test, I reproduced the crash an solved it, it happens when autocomplete at beginning of files, if you go in the second line it works 👍 

I will do some test and will release the 0.8.3

**Comment by Bacco** [comment]
I'm a little busy lately, and I just migrated to VS Code recently, but
hope I can contribute with the project in near future.
I'll test ASAP when you release 8.3.

Thank you for your dedication and generosity toward the community.

Best Regards,
Bacco
