### ISSUE TITLE
Ctrl+P # seems not working while @ works

### ISSUE THREAD

**Issue by lfiorini** [APerricone/harbourCodeExtension#11]
After the fresh start the list is empty, then it starts to show one/two sources and it finds few functions in those sources only. Could it be the structure of my workspace? Let me know if you need more info. Regards.

**Comment by APerricone** [comment]
Hello,
I see 3 possibilities:
1. You have very big file and do the search too soon so the files are not completely parsed.
2. You have sources in multiple subdirectory, the extension actually looks only on workspace paths, you can add more then one directory on the current workspace... see #9 . I undestand that if the directory is one sub dir of other it is not the most comfortable way... maybe I will add another setting for search in subdir.
3. I don't understand your problem. :)

**Comment by lfiorini** [comment]
Thanks for your reply.

1. I've tried with small prg files, same result.
2. Yes I have multiple subdirs but they are inside the same root. I'm not sure I understand what you mean with workspace paths. Which setting should I check?
What I see is that when I type Cmd+P and then @ I see immediately a symbol list. If in the same source I type Cmd+P # the list opens but completely empty.

Regards.

**Comment by lfiorini** [comment]
I see that you're working on this issue. Many thanks. Just for your information I often use it by mistake since I'm used to it using C#. I cannot see a pattern but sometimes I get a list of symbols from sources that are in subdirs but the list is incomplete. It seems it looks only in few sources but if I choose those symbols it works as expected.

Regards.

**Comment by APerricone** [comment]
It is possible that the symbols you see are in files you opened?

**Comment by lfiorini** [comment]
As I told I cannot see a clear pattern. What is strange it seems that it finds "better" inside the function name but it is "worse" if I type the begin of the name. For example it miss a function called INSART even if I have open the source: the list skip from G to k and shows also other sources. But it could be also completely random.

Regards.

**Comment by APerricone** [comment]
I added the setting, **harbour.workspaceDepth** to control the sub-folder parsing.
It should fix this issue

**Comment by lfiorini** [comment]
Many thanks. I'm testing it and it seems ok. It doesn't find 3 letters functions like reg( or doc( is it expected?

Regards.

**Comment by APerricone** [comment]
Today I was debugging a case of symbol not found, I see my extension returns at most 100 result, if they are more you must add some characters to found the method.
An ideal solution for this is https://github.com/Microsoft/language-server-protocol/issues/307 but is still not implemented.

**Comment by lfiorini** [comment]
> On 6 Feb 2019, at 14:11, Antonino Perricone <notifications@github.com> wrote:
> 
> Today I was debugging a case of symbol not found, I see my extension returns at most 100 result, if they are more you must add some characters to found the method.
> An ideal solution for this is Microsoft/language-server-protocol#307 but is still not implemented.
> 
Don’t worry, 0.8.6 is a great improvement at least foe me. Finding the symbol simply with Cmd+T looks much like F12 Goto Definition possible in other languages.

Regards.

**Comment by APerricone** [comment]
"Go to definition" should works :(

**Comment by lfiorini** [comment]
On Wed, Feb 6, 2019 at 8:40 PM Antonino Perricone <notifications@github.com>
wrote:

> "Go to definition" should works :(
>
Many thanks. I tried time ago and it didn't work so I assumed it couldn't
be implemented.
BTW is there a way to exclude .hbmk C sources?
It seems to find both the HB_FUNC( funcname ) in x.c and function funcname
in x.prg.

Regards,

>

**Comment by APerricone** [comment]
I see, it is annoying, I open #12 about that. I think I will release a new version this week to fix it.
