### ISSUE TITLE
In symbol search, is looking for methods useful?

### ISSUE THREAD

**Issue by lfiorini** [APerricone/harbourCodeExtension#14]
Since we cannot distinguish from different classes ( it is simply a text search ), I' wondering if it is useful to report method's names in Goto Symbol. Names like init, end, close are used in almost every class. Also we use the method keyword both in the declaration and in the implementation, so they are reported twice.

On the other side if you have a method name specific to a single class it could be useful to find it.

Any comment?

Regards.

**Comment by APerricone** [comment]
in harbour most of time there is not a way to determine which class is it, the only case is possible is when the new is some line above... 
about declaration and definition I am working on it,  Ideally It can use [go-to-declaration](https://code.visualstudio.com/updates/v1_30#_go-to-declaration) feature... but I did not have time to work on it
