### ISSUE TITLE
Harbour format

### ISSUE THREAD

**Issue by rjopek** [APerricone/harbourCodeExtension#15]
Hi Antonino,

I see that you do not follow the Harbor format adopted rules Alexander S.Kresin

Rafał

**Comment by APerricone** [comment]
Hello,
"Mighty strong words, runt! You man enough to back them up with more than just a pie plate?" 🤣 
I don't know what are you talking about... 😕 
Can you provide a link or something that explain?
Thanks,
Antonino

**Comment by rjopek** [comment]
It's a good program for formatting the source code, several standards have been adopted here.
[hbformat](https://github.com/harbour/core/tree/master/contrib/hbformat)

When it comes to formatting the source code for your project, suggest to copy ready-made elements from the C language.

P.S.
The link you submitted is not a problem for your project.
Rafał
