### ISSUE TITLE
Not giving me suggestions based on words on my Document

### ISSUE THREAD

**Issue by riverbr** [APerricone/harbourCodeExtension#16]
In version 0.8.7, it's not giving me suggestions based on words that is present on my code

exemples:
Version 0.8.5
![sem titulo](https://user-images.githubusercontent.com/25988914/52901092-351ae800-31dd-11e9-8354-7234f95bab87.png)

Version 0.8.7
![2](https://user-images.githubusercontent.com/25988914/52901112-70b5b200-31dd-11e9-8e96-d942e9ab951a.png)

Why this is happening?

**Comment by APerricone** [comment]
fixed in 0.8.8. stay tuned

**Comment by riverbr** [comment]
thanks :3

**Comment by leonardonr** [comment]
I'm using v0.9.13 and sometimes IntelliSense stops working
