### ISSUE TITLE
Debugger doesn't have option to launch in Terminal

### ISSUE THREAD

**Issue by jbtule** [APerricone/harbourCodeExtension#17]
Debugger doesn't have option to launch in Terminal, for console gui style programs.  An attach to running program could also solve this problem.

**Comment by APerricone** [comment]
I am working on it, the 0.8.8 should have it, probably it will be include the "attach" mode.

It will be necessary update the dbg_lib.prg, of course.

**Comment by APerricone** [comment]
added in 0.8.9
