### ISSUE TITLE
Use Typescript instead Javascript

### ISSUE THREAD

**Issue by edgardmessias** [APerricone/harbourCodeExtension#22]
Typescript has a lot of advantages to use

**Comment by APerricone** [comment]
no, there are none

**Comment by edgardmessias** [comment]
If you allow it, I can do the conversion when I have time.

**Comment by APerricone** [comment]
Typescript needs to be translated to Javascript to be executed...
So, you want translate Javascript in Typescript, that will be translate in Javascript?
