### ISSUE TITLE
Can't compile when debugger code is included on my project

### ISSUE THREAD

**Issue by riverbr** [APerricone/harbourCodeExtension#27]
When I include the debugger code on my project (debugador.prg), it returns me an error. The -b switch is active in my HBP files. errors attached
[build.log](https://github.com/APerricone/harbourCodeExtension/files/3139135/build.log)
[hb_out.log](https://github.com/APerricone/harbourCodeExtension/files/3139160/hb_out.log)

**Comment by APerricone** [comment]
Can you try to update the debugador ? 
and if it crashes anyway (probably) send the hb_out.log again.
Thanks.

**Comment by riverbr** [comment]
> Can you try to update the debugador ?
> and if it crashes anyway (probably) send the hb_out.log again.
> Thanks.

how can I update? using the command Get dubbuger code?

**Comment by APerricone** [comment]
exactly

**Comment by riverbr** [comment]
done. it compiles, generates an executable, but the program don't show up. it's not generating the log file. if I remove the prg from my HBP, everything works fine

**Comment by dmwysocki61** [comment]
I have a similar problem.  I have one statement related to the QT add on in the HelloHarbour.prg. 

#include "hbqtgui.ch"

I added this statement to the program and then compiled and linked the program. When I start the program in debug mode, it stops and highlights line 1323 in the debugger.prg. When I then clicked on the Step Into button, the error message is thrown. I'll send the same to your email.

My program is stopping at line 1323 of the debugger program. Following is a snip of the code which is part of the case statement:

case HB_DBG_SHOWLINE

The line where the program stops starts here:

#ifndedf __ XHARBOURT__ //temp
    **if empty(tmp) .or. empt(t_oDebugInfo[..................**

When I click on the step into button, I get the following error message:

Error BASE/1070 Argument error: ==
Called from ERRORBLOCKCODE(1182)
Called from (b)__DBGENTRY(1334)
Called from __DBGENNTRY(1323)
Called from Main(6)

This fails before the first break point at the beginning of HelloHarbour.prg program. 

Please let me know if there's any additional info I can provide that will help resolve this issue.

Thanks for your help

**Comment by APerricone** [comment]
excuse me, where do you see XHARBOURT__  ? and empt( ?

**Comment by dmwysocki61** [comment]
Lines 1322 and 1323 is as follows:
#ifndef __XHARBOUR__ //temp        if empty(tmp) .or. empty(t_oDebugInfo['errorBlock']) .or. !(t_oDebugInfo['errorBlock']==tmp)

I had tried to highlight the lines I was referring to but maybe the browser added extra characters. 
Dave Wysocki Diversified Tech Systems,Inc. 954-328-3328 

    On Tuesday, November 12, 2019, 08:49:28 AM EST, Antonino Perricone <notifications@github.com> wrote:  
 
 
excuse me, where do you see XHARBOURT__ ? and empt( ?
