### ISSUE TITLE
Version 0.9.0 - Code: -32603

### ISSUE THREAD

**Issue by riverbr** [APerricone/harbourCodeExtension#28]
Returning error on output screen when holding Ctrl and moving the cursor on the editor
Error log:
[Error - 10:30:37] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'toLowerCase' of undefined
  Code: -32603

**Comment by APerricone** [comment]
I already fixed it, but it is too annoying.
Release 0.9.1

**Comment by riverbr** [comment]
thanks! It was really annoying
