### ISSUE TITLE
Extending Variables view in debugger to show Workareas

### ISSUE THREAD

**Issue by Delapro** [APerricone/harbourCodeExtension#29]
Hi!

From other harbour-debuggers I'm used to see my Workareas. So I can check current record number, indexes and filter settings...

Maybe you could extend your Scope-Variables (variableCommands in debugger.js) to transfer WORKAREAS?

With WORKAREAS I could extend debugger.prg to send the required Information to the vscode-debugger-view. It should react like objects with propertyname and value, so I can project the current settings and the current values of the current record.

Thanks! And keep up the great work!

**Comment by APerricone** [comment]
I will implement it if it gain 10 thumbs up

**Comment by APerricone** [comment]
I implemented it, I am debugging. here a preview:
![image](https://user-images.githubusercontent.com/22457168/158753373-c7cc2048-febb-47e8-8229-d77619444ba2.png)
The first area is the selected one, then all other sorted by area number. I added some information. a table vision is too much work and dangerous.

**Comment by dmwysocki61** [comment]
The only suggestions I have to add are the following:
1. Show the open index

Great extension, I have it working and it has already paid off tremendously!

**Comment by APerricone** [comment]
What do you mean for "open index"? it is not the scope? or do you mean ordKeyVal?

**Comment by APerricone** [comment]
close this as implemented on 1.0.2
