### ISSUE TITLE
Dont' trace include files

### ISSUE THREAD

**Issue by VictorCasajuanaMas** [APerricone/harbourCodeExtension#30]
When the file.prg have a include file, the debug don't show step by step the include file but it's procesed, and when the process terminate inclide file, the ponter not return at file.prg

I attach test.prg test.inc and make.bat for the test.

[test.zip](https://github.com/APerricone/harbourCodeExtension/files/3216209/test.zip)

**Comment by APerricone** [comment]
probably it is an Harbour issue

**Comment by APerricone** [comment]
fixed in the last commit... with wrong issue number 
https://github.com/APerricone/harbourCodeExtension/commit/9b818874a89bfd3b489c6516f7c13cb73912029d
