### ISSUE TITLE
extension v0.9.3, VSCode v1.36.1, error code -32603

### ISSUE THREAD

**Issue by Pledkae** [APerricone/harbourCodeExtension#34]
Just opening .prg files outputs bunch of following errors in Harbour Server Output:

`[Error - 14:54:11] Notification handler 'workspace/didChangeConfiguration' failed with message: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "null", query: "", fragment: ""}
[Error - 14:54:11] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "null", query: "", fragment: ""}
  Code: -32603`

No problems with the extension version 0.9.2

**Comment by APerricone** [comment]
This part is not changed between 0.9.2 and 0.9.3, it happens every time open a prg? first time you open a prg? or when, with a prg opened you change a setting?

**Comment by Pledkae** [comment]
Here are some more details:

This message:
`[Error - 14:03:48] Notification handler 'workspace/didChangeConfiguration' failed with message: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "null", query: "", fragment: ""}`
is shown in output whenever i open a new .prg in existing VS Code instance, whenever I start VS Code with .prg tab in focus (if tab with file with different extension is in focus, then error message does not appear, but it does the very moment I select a tab with opened .prg file). This message shows only once and if I close the Harbour Server output it doesn't reappear until I restart VS Code.

The other messages, with `Code: -32603` are shown every few seconds, depending on typing or hovering with mouse, but only in case hover is enabled in VS Code settings:

![Code_2019-07-19_14-02-08](https://user-images.githubusercontent.com/7941856/61534736-b1d21c80-aa30-11e9-8e7f-d9af0362c186.png)

If I disable settings highlighted in the above screenshot, `Code: -32603` messages do not appear.

Example messages (three different ones: textDocument/hover, textDocument/definition and textDocument/definition) are:
`[Error - 14:17:09] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "null", query: "", fragment: ""}
  Code: -32603 `
`[Error - 14:17:10] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "null", query: "", fragment: ""}
  Code: -32603`
`[Error - 14:20:33] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "null", query: "", fragment: ""}
  Code: -32603`

`Code: -32603` messages are shown constantly in output regardless of closing the output, it just reopens itself.

If there are any other settings/outputs/logs which might help with this issue, please let me know and I'll paste them here.

**Comment by Pledkae** [comment]
Status update: VS Code v1.38.0; Harbour and xHarbour extension v0.9.4: no more errors. If line in changelog "server better performance, stability + some fixes (#32)" is related to this, the issue can be closed.

**Comment by APerricone** [comment]
I forgot this issue :(
I found same problem working without open a work folder.
I solved it.
