### ISSUE TITLE
Setting breakpoints issue

### ISSUE THREAD

**Issue by lfiorini** [APerricone/harbourCodeExtension#35]
In my setup, setting breakpoints from VS Code UI never work while altd() works. I've done a little research using _DEBUGDEBUG define and it seems that setBreakPoint receives from UI the filename without path while in t_oDebugInfo['aStack'] it is stored relative path of the prg during the compilation (so it can somewhat misleading). Is setting BPs supposed to work even in case that prgs are not in the root dir?

**Comment by APerricone** [comment]
I understand the issue, the information about where is the breakpoint comes from VSCode, the information about the stack comes from Harbour's VM. So they can mismatch... as plus on windows the filename is case insensitive... 
I know how fix it...
