### ISSUE TITLE
MacOs Could not load source '...'

### ISSUE THREAD

**Issue by lfiorini** [APerricone/harbourCodeExtension#36]
In MacOs the same code and the same setup that I use in Windows doesn't load the source file with the message Could not load source '...'. The path and the file name reported in '...' is correct. launch.json is the exactly the same and I start from exactly the same git folder so the relative paths are the same.

**Comment by APerricone** [comment]
In case of error, on the stack there is an element with the same name of executable, it is annoying but other elements works... is this the case?
maybe it is relative to #35 ?
are you sure the path is correct? maybe you can try to do copy and paste in open file dialog... I am not sure you can do copy...

**Comment by lfiorini** [comment]
The path that is shown is correct and the code is exactly the same as in Windows. If you could point me to the JS part that loads the source I could do few tests.

**Comment by APerricone** [comment]
The code that tests the existing of source code is https://github.com/APerricone/harbourCodeExtension/blob/27b99de744e94be62f952bb2fb955db8951ac42d/client/src/debugger.js#L357

to debug the debugger.js you can start the "Debbuger"" configuration from client and start an application with the options "debugServer": 4711 in the launch.js

**Comment by lfiorini** [comment]
Many thanks, I'll do some tests and will report.

**Comment by lfiorini** [comment]
Sorry probably I misunderstood what I need to do. What do you mean for "Debugger configuration"?

**Comment by APerricone** [comment]
open the client folder (the one with package.json) with Code, and in debug select Debugger
![image](https://user-images.githubusercontent.com/22457168/61872695-572f3980-aee4-11e9-8fac-12f8fc6a3473.png)
and in launch.json add debug server:
![image](https://user-images.githubusercontent.com/22457168/61872781-7cbc4300-aee4-11e9-83d4-775b55e12f5a.png)

**Comment by lfiorini** [comment]
If run vscode twice in this way it shows the source:
1) go to ~/.vscode/extensione/aperricone... code .
2) go to my dir, run code . and start the debug.
Without touching launch.json.
I have found it by accident while I was looking in the debugger.js. It is repeatable and I've also restarted the Mac to be sure. I understand it sound crazy...

**Comment by lfiorini** [comment]
I've tried with debugServer: 4711 but it doesn't start and shows and alert with "connect ECONNREFUSED 127.0.0.1:4711"

**Comment by APerricone** [comment]
I did not understand

**Comment by lfiorini** [comment]
What I wrote or why it happens?

**Comment by APerricone** [comment]
what You wrote

**Comment by lfiorini** [comment]
I understand that it could be difficult. It seems a typical problem of "not clean startup". If vscode is already working (strangely in a very specific dir) and I open another instance it shows the source, if I start it "alone" it says Could not load the source.

**Comment by lfiorini** [comment]
If I start vscode closer to the prgs ( in the parent dir ) it shows the sources. While if I start in the root of the repo like in Windows it can't find the sources. Of course I had to create another debug configuration. I've tried to change sourcePaths and workingDir but without success.

**Comment by APerricone** [comment]
now it has sense. :)
you must fix the sourcePaths setting. remeber that is concatenated to not found source in the stack.
If the source is not found, the debugger shows the complete getted path.
so if in the stack you see, for example, "../../src2/group1/source3.prg" you can set the source path to "/dev/myproject/src1/group1" that with concatenation become: "/dev/myproject/src1/group1/../../src2/group1/source3.prg" then "/dev/myproject/src2/group1/source3.prg" obviusly it is an example.
the problem is how you specify the source to harbour executable.

**Comment by lfiorini** [comment]
I tried several changes in sourcePaths in the Mac but the path reported by Could not load source '...' is the correct relative path to the source and with the same launch.json, the same git repo works as expected in Windows.
However it is not a big problem, there is a workaround and you can close the issue if you want.
Many thanks for your great work on this extension.

**Comment by APerricone** [comment]
you can specify sourcePath (and other parameter) different for platform: for example:
```js
      {
         "type": "harbour-dbg",
         "request": "launch",
         "name": "Launch Program",
         "program": "${workspaceRoot}\\Program",
         "windows": {
            "workingDir": "C:\\dev\\testDir",
            "sourcePaths": ["${workspaceRoot}","c:\\libSrc"]
         },
         "linux": {
            "workingDir": "/dev/testDir",
            "sourcePaths": ["${workspaceFolder}","/dev/libSrc"]
         },         
         "arguments": [],
         "stopOnEntry": false,
         "preLaunchTask": "build_Debug"
      },
```

I think you can write the the file path that appears in the stack and the correct path, so I can help you to configure sourcePaths

**Comment by lfiorini** [comment]
Here is the screenshot:
<img width="1198" alt="Screenshot 2019-07-29 at 17 31 52" src="https://user-images.githubusercontent.com/3235634/62061332-3c7ffc00-b227-11e9-8fbe-d02a639030da.png">

**Comment by APerricone** [comment]
looks like i missing a slash / at beginning 
The path of the source is correct?

**Comment by lfiorini** [comment]
If you mean the path dothrb/..., it is correct. It is the relative path starting from workspaceRoot.
