### ISSUE TITLE
Formatter support?

### ISSUE THREAD

**Issue by peternm22** [APerricone/harbourCodeExtension#37]
I tried running Shift-Alt-F on a Harbour file and I get the error "There is no formatter for 'harbour'-files installed."

It doesn't look like your extension supports formatting files (please correct me if I am wrong). Would there be any way you could add this feature to the extension?

**Comment by APerricone** [comment]
I will implement it if it gain 10 thumbs up

**Comment by micaelaad** [comment]
Hello!
When do you pretend to implement this?? We are needing a lot

**Comment by APerricone** [comment]
ops... it arrived to 10 thumbs up!! unbelievable.
I will work on it from this weekend!

**Comment by APerricone** [comment]
it is present on beta on 1.0.2, close it and keep open bug reports like #79
