### ISSUE TITLE
xHarbour Debugging

### ISSUE THREAD

**Issue by Flexa-B** [APerricone/harbourCodeExtension#38]
Hi there,

I am trying to get debugging up and running for my xHarbour project, but I'm having some issues with the debugger code. When compiling the code, I get three external symbol errors:

```
xLINK: error: Unresolved external symbol '_HB_FUN_HB_TSTOSTR referenced from (debugger.obj)'.
xLINK: error: Unresolved external symbol '_HB_FUN_HB_PS referenced from (debugger.obj)'.
xLINK: error: Unresolved external symbol '_hb_stackGetRecoverBase referenced from (debugger.obj)'.
xLINK: fatal error: 3 unresolved external(s).
```

Could just be that I am new to the language, but I'm having trouble finding the issue. Doing some digging online, I think it could be that the project isn't using the latest version of xHarbour and that these functions are not in our version, but I thought I'd ask.

Any info would be great, thanks!

**Comment by APerricone** [comment]
hello,
xHarbour have a big issue with the debugger, [I asked to community without luck](https://groups.google.com/d/topic/comp.lang.xharbour/OuO9YQfzAXI/discussion) then I forgot the problem. I keep this issue as remember note.

What version of xharbour are you using? hb_TsToStr is present in xHarbour 1.2.3 I am using (20181011)
The hb_ps must be substitute with hb_osPathSeparator, i will do a commit about it.

**Comment by Flexa-B** [comment]
Gotcha. I'll keep an eye out on the status of the debugger going forward.

Looks like the version we are using is quite out of date (xHarbour 1.2.3 (Build 20131030)), and I think that the hb_TsToStr was added sometime in 2015, so the solution to my specific issue is probably to just look into upgrading our codebase, or seeing if I can replace that function with something similar.

Thanks for the help!
