### ISSUE TITLE
Variables are no more showed up in debugger

### ISSUE THREAD

**Issue by mlacecilia** [APerricone/harbourCodeExtension#47]
The variables other than arrays and objects are no more displayed at debugging time.
More precisely, the array items and objects data are also affected by the issue.
All the scalar values (C, D, N, L) of any scope are displayed without name and the "Invalid variable attributes" error message.
The debugger is working fine.
The only change I done was to migrate to VSCodium. There's some incompatibility between the two applications? That shouldn't happen AFAIK.

![image](https://user-images.githubusercontent.com/2537130/74735771-a4dd0c00-5251-11ea-8974-dfa046fdba10.png)

**Comment by APerricone** [comment]
No, the latest version od VSCode has the same issue, I am working on new version, so when it come out the probilem will be fixed

**Comment by APerricone** [comment]
fiex on c0da183d245acc6f1ab33c2bade6e7a0a42b7c7b

**Comment by APerricone** [comment]
fixed on 0.9.10

**Comment by mlacecilia** [comment]
Hi Antonino,
surely something went wrong on my side but, after updating to 0.9.10, the debugger stops at breakpoints as expected but it doesn't display current source line, variables, watch, call stack and the control for stepping/stopping the execution. Only a "Canceled" message appears and disappears in less than a second. Any hint? TIA
![image](https://user-images.githubusercontent.com/2537130/75259842-f274ee00-57e8-11ea-851f-f528a7196d6c.png)
