### ISSUE TITLE
High cpu usage MacOS

### ISSUE THREAD

**Issue by l41lt0n** [APerricone/harbourCodeExtension#5]
Hi Perricone,

Please take look on it:
https://github.com/Microsoft/vscode/issues/47676

Thanks

**Comment by APerricone** [comment]
Hello, 
I think the problem is the number of files, what folder did you open? how many files prg there in it? how many subfolders? how many prg on subfolders? 
I am planning to include the loading of .gitignore, .ignore and the setting search.ignore to avoid parsing some file and folder...
Antonino

**Comment by l41lt0n** [comment]
@APerricone 

It has a lot of file. I have no idea total, but is more than one thousand ( files/folder/subfolders )

Ignore look be a good idea.

Thanks

**Comment by APerricone** [comment]
Hello,
as temporary fix I removed the subfolder parsing, It bothers me at work with a big projects...
