### ISSUE TITLE
debugger crash on 0.9.10

### ISSUE THREAD

**Issue by APerricone** [APerricone/harbourCodeExtension#52]
Hi Antonino,
surely something went wrong on my side but, after updating to 0.9.10, the debugger stops at breakpoints as expected but it doesn't display current source line, variables, watch, call stack and the control for stepping/stopping the execution. Only a "Canceled" message appears and disappears in less than a second. Any hint? TIA
![image](https://user-images.githubusercontent.com/2537130/75259842-f274ee00-57e8-11ea-851f-f528a7196d6c.png)

_Originally posted by @mlacecilia in https://github.com/APerricone/harbourCodeExtension/issues/47#issuecomment-590913374_

**Comment by APerricone** [comment]
It is the second report about the debugger crash, both very similar... I am working on it

**Comment by Gisleno-Br** [comment]
i got this error too , when i instaled harbour extension on my vs code.

**Comment by mlacecilia** [comment]
Hi Gisleno,
in my case it wasn't a extension issue, but a wrong path in my sourcePaths
setting.
JFYI
--
Maurizio

Il ven 6 mar 2020, 16:16 Gisleno-Br <notifications@github.com> ha scritto:

**Comment by Gisleno-Br** [comment]
I Tried to solve the problem by changing the sourcePaths , But it didn´t Work. If you can show me your
launch.json , maybe it Will be a Good Help for me, Thanks.

**Comment by mlacecilia** [comment]
Here is it:

{
    // Usare IntelliSense per informazioni sui possibili attributi.
    // Al passaggio del mouse vengono visualizzate le descrizioni degli attributi esistenti.
    // Per ulteriori informazioni, visitare: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "type": "harbour-dbg",
            "request": "launch",
            "name": "wce",
            "stopOnEntry": true,
            "program": "${workspaceFolderBasename}.exe",
            "sourcePaths": [ "${workspaceFolder}", "${workspaceFolder}/../hbsys" ],
            "workingDir": "/cg7"
        },
        {
            "type": "harbour-dbg",
            "request": "launch",
            "name": "hbBuild",
            "program": "${workspaceFolder}/../hbsys/hbbuild.exe",
            "arguments": [
                "${workspaceFolderBasename}"
            ],
            "workingDir": "${workspaceFolder}/",
            "sourcePaths": [
                "${workspaceFolder}/../hbsys"
            ]
        }
    ]
}

**Comment by Gisleno-Br** [comment]
Thank´s , I Will test.

**Comment by APerricone** [comment]
There is some issue with the library true-case-path, I just tried with a not existing "sourcePath" and this dialog appears:
![image](https://user-images.githubusercontent.com/22457168/76112991-988fd780-5fe3-11ea-8ef6-a9f8ce006f78.png)

But I can't crash it like you do.

**Comment by Gisleno-Br** [comment]
I saw This error Too on my Vs Code in some of my tries to Fixe It.

**Comment by mlacecilia** [comment]
Sorry for jumping in, but I would advice about a new issue I'd found using 0.9.10
The debugger now is skipping the current line as expected, but in some cases it's pointing to the wrong prg source.
IOW, the callstack shows the right line, but the wrong prg source. Also the current highlighted line is shown in the wrong source in the editor window.
The variables, indeed, are working flawlessy.

![image](https://user-images.githubusercontent.com/2537130/76115974-61bcc000-5fe9-11ea-888e-4a9c950265fb.png)

**Comment by APerricone** [comment]
maybe the 2 sources have same name and different path? or are you including prg files? that are 2 cases I already saw but I think are too much uncommon

**Comment by mlacecilia** [comment]
not at all. each prg has unique name and are present in two different folders.
In my screenshot hbs_getlist:reader and hbs_getlist:readmodal are both in the hbs_getlist.prg file, prg11 is present in wce1.prg (totally absent in callstack). IOW the file references are totally messed.
About including of prg files, after the previous issue I've signaled some time ago, I changed that approach and now all is linked separately as prg file.

**Comment by Gisleno-Br** [comment]
Hi , 

Do i Have to update debugger.js to Apply the Solution to the Issue?

**Comment by APerricone** [comment]
Hello, you can not update debugger.js, it is an element of the extension.
My commit solves this:

> ![image](https://user-images.githubusercontent.com/22457168/76112991-988fd780-5fe3-11ea-8ef6-a9f8ce006f78.png)
> 

But I am not able to reproduce the crash, so I can not fix it.  If you problem is systematic, I can provide a beta version of my extension with this trying fix. Maybe it works.
You can see my email on [my profile](https://github.com/APerricone), and I can send you a beta by email

**Comment by Gisleno-Br** [comment]
Hello,

Ok , I will send you a Email , So you can send me the Beta Version. If it doesn´t Work , MayBe it´s a Problem with the version Harbour i am Using . A Update of the Harbour version can solve the problem.

 Thank´s

**Comment by Gisleno-Br** [comment]
I Changed the Version to 0.9.9 and The debuuger is Working fine. There is Something Wrong with the 0.9.10 , I Think.
