### ISSUE TITLE
For next code collapse 

### ISSUE THREAD

**Issue by Hovestar** [APerricone/harbourCodeExtension#56]
For .. Next will collapse to a variable that starts with next:
![image](https://user-images.githubusercontent.com/3644064/76094778-2b535680-5f91-11ea-925c-280f0d301411.png)
![image](https://user-images.githubusercontent.com/3644064/76094806-37d7af00-5f91-11ea-8765-59d7dbcc8915.png)

**Comment by APerricone** [comment]
cool, I can say more, if you put the cursor on "for" word the "next" inside next_marker is highlighted
