### ISSUE TITLE
What should do Harbour: Get debugger code? 

### ISSUE THREAD

**Issue by lfiorini** [APerricone/harbourCodeExtension#6]
Harbour: Get debugger code does nothing on MacOS 10.14. Is it expected?

**Comment by APerricone** [comment]
Thank you for your reporting
The command should create a new harbour file with inside the code https://github.com/APerricone/harbourCodeExtension/blob/7e3e8bf8410ab5f09634ec2bb8fd167606c14fae/test/dbg_lib.prg, that is necessary for use integrated debugger.

in a piece of code i use \ as directory separator, it is wrong in Mac and Linux, i will fix it on next release.
