### ISSUE TITLE
Try catch syntax highlighting

### ISSUE THREAD

**Issue by Hovestar** [APerricone/harbourCodeExtension#60]
![image](https://user-images.githubusercontent.com/3644064/77765367-8dddc680-7014-11ea-8248-3811d9213ac6.png)
![image](https://user-images.githubusercontent.com/3644064/77765433-a2ba5a00-7014-11ea-8907-5ef917c5642e.png)

**Comment by APerricone** [comment]
fixed with ca15a4564e19cd164b9e035692e28f710ba147d6
