### ISSUE TITLE
High CPU use caused by presence of certain PRG

### ISSUE THREAD

**Issue by EricLendvai** [APerricone/harbourCodeExtension#68]
Hello Antonino,

Thank you so much for your extension.

I think I found a bug related to the code linter/syntax verification engine.
If you have a .prg file in your folder, not even open it, and it has an instruction with more than 2000 lines, like a huge hash array assignment, the CPU usage will go way up, and will not come down until you exit all VSCODE instances. Attached a file that creates the problem.

For now my work around  is to rename the .prg to a .txt and use a #include to bring in the file at compile time.

[ProgramFileCreatingHighCPUUseV3.zip](https://github.com/APerricone/harbourCodeExtension/files/5908471/ProgramFileCreatingHighCPUUseV3.zip)

**Comment by APerricone** [comment]
very nice catch! There is a bug on parser that re-parse all the agglomerated line every sub line... Anyway, I will do a fix for it.

**Comment by EricLendvai** [comment]
Thank you Antonino. Is there a way to include the vsix file in your repo, to make it possible to use this fixed version before you publish an official new version ?

**Comment by APerricone** [comment]
with e733b62def808d5af653a79b1897fc38b54046c5 the performance on sample file got a very big boost, check it out :)
