### ISSUE TITLE
Error on starting 0.9.16

### ISSUE THREAD

**Issue by mlacecilia** [APerricone/harbourCodeExtension#70]
(node:10768) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir 'SVN\'
    at readdirSync (fs.js:959:3)
    at e.readdirSync (electron/js2c/asar_bundle.js:5:10231)
    at c:\Users\Maurizio\.vscode\extensions\aperricone.harbour-0.9.16\server\dist\hb_server.js:1:175328
    at Array.reduce (<anonymous>)
    at c:\Users\Maurizio\.vscode\extensions\aperricone.harbour-0.9.16\server\dist\hb_server.js:1:175306
    at Object.trueCasePathSync (c:\Users\Maurizio\.vscode\extensions\aperricone.harbour-0.9.16\server\dist\hb_server.js:1:175341)
    at i (c:\Users\Maurizio\.vscode\extensions\aperricone.harbour-0.9.16\server\dist\hb_server.js:1:41104)
    at e (c:\Users\Maurizio\.vscode\extensions\aperricone.harbour-0.9.16\server\dist\hb_server.js:1:41398)
    at c:\Users\Maurizio\.vscode\extensions\aperricone.harbour-0.9.16\server\dist\hb_server.js:1:41196
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:10768) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 90)

**Comment by APerricone** [comment]
you probably have a nonexistent path in your settings ... I would never find this crash.

**Comment by mlacecilia** [comment]
I'll control, but I think that the path is right and downgrading to 0.9.13
the error vanishes. Maybe some recent change is requiring a complete path?
Surely I'm using relative paths.

Il lun 15 feb 2021, 19:52 Antonino Perricone <notifications@github.com> ha
scritto:

**Comment by APerricone** [comment]
No, that part is unchanged from 0.5.0 , I just check the history

**Comment by APerricone** [comment]
It is a very strange error, before the crashing point there are a couple of fs.existsSync so the file exists, but trueCasePath goes in crash, luckily I used this library to increase the stability of the code... I put that part inside a try/catch as I did for #52, the new versions have a better management of the includes, from 8bf238380b78b9054d9eed49551df4f6ef6fd1d6 maybe it is the trigger that starts the crash.
Anyway, it gives me an excuse to release the 1.0.0 :)
