### ISSUE TITLE
launch a batch

### ISSUE THREAD

**Issue by dannythevii** [APerricone/harbourCodeExtension#72]
Dear ms. Perricone

is possible to launch a personal bat file for the compilation but how i can close the  console debug automaticly ?

also. is possible to assign a fast-key to a specific task ( like F9 ) ?

thanks in advance.

Ma per casso sei italiano ? :-)

**Comment by APerricone** [comment]
Hello, your question are most about the use of VSCode, it is all explained in [this page](https://code.visualstudio.com/docs/editor/tasks#_custom-tasks). Take a look there and if you don't be able to resolve it write here, i will keep this issue open another couple of days.
Regards.
PS. sì, sono Italiano, non per casso ;)

**Comment by dannythevii** [comment]
perdonami per il casso, non era intenzionale.
cmq proprio non riesco

il comando in launch.json òè questo
        {
            "command": "C:\\Harbour\\DarioWeb\\compila.bat ",
            "name": "Run dario",
            "type": "node-terminal",
            "request": "launch",
        },

e funziinna, ma lascia quel cavolo di finestra aperta, 
esiste qualcosa per chiuderla?
per info, lavoricchio in minigui extend

Grazie Antonino

**Comment by APerricone** [comment]
il tipo è sbagliato. il file .bat non sono di node, devi mettere tipo shell, guarda https://github.com/APerricone/harbourCodeExtension/blob/aa3e4f831993f2f89e7389a7f2d5646ac19b2620/test/.vscode/tasks.json è come compilavo prima, poi ho creato il tipo HBMK2 anche se non l'ho mai documentato.
