### ISSUE TITLE
sorry but 1.0.2 is badly messing my code

### ISSUE THREAD

**Issue by lfiorini** [APerricone/harbourCodeExtension#79]
Not only formatting but it messed up with comments /* ... */ and results into many syntax errors.
Went back to 1.0.1.

**Comment by APerricone** [comment]
can you post some screenshot or code sample?

**Comment by lfiorini** [comment]
As far as I could see (before the downgrade) it replaced some */ with //// so big parts of the code resulted commented. Also the format of the code was heavily changed resulting in tons of diffs. I'll setup a test environment and I'll see if I can help.

**Comment by APerricone** [comment]
Maybe I understand, but usually the formatting is not automatic, anyway, ok, I will fix it.

**Comment by lfiorini** [comment]
Thank you, I see that you work on the issue. BTW is the formatting on by default? I was coding and I even didn’t notice the upgrade (I use many extensions so updates are the norm  and in fact it took me a while to understand the source of the problem).
Please let me know when you want me to start the tests.

**Comment by APerricone** [comment]
it should be fixed with https://github.com/APerricone/harbourCodeExtension/commit/bf0775914a06eb45a0b6138c0300aaac1c2052e8

**Comment by lfiorini** [comment]
👍
