### ISSUE TITLE
Lint and -ge1

### ISSUE THREAD

**Issue by lfiorini** [APerricone/harbourCodeExtension#8]
I use the parameter -ge1 to get harbour compiler error messages in gcc format so I can use:

"problemMatcher": {
        "owner": "cpp",
        "fileLocation": "absolute",
        "pattern": {
          "regexp": "^(.*):(\\d+):\\s+(.*)$",
          "file": 1,
          "line": 2,
          "message": 3
        }
      }

Could you kindly point me where I could change the error parsing regexp in the extension code?

**Comment by APerricone** [comment]
Hello,
in task.json, you can write 

   "problemMatcher": "$harbour"

that is converted in:

"problemMatcher": {
                "name": "harbour",
                "owner": "harbour",
                "fileLocation": "relative",
                "pattern": {
                    "regexp": "^(?:([^\\(]*)\\((\\d+)\\)\\s+)(Warning|Error)\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "severity": 3,
                    "message": 4
                }
            },
And it works without -ge1 argument,

If it is necessary, i will add a problem matcher that works with -ge1
is it necessary?

**Comment by APerricone** [comment]
I forgot, You can specify more than one problem matcher, for example in my project I have:
```
"problemMatcher": [
            {
                "owner": "cpp",
                "fileLocation": [
                    "relative",
                    "${workspaceRoot}"
                ],
                "pattern": {
                    "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            }, "$harbour"]
```

**Comment by lfiorini** [comment]
> If it is necessary, i will add a problem matcher that works with -ge1
> is it necessary?

Absolutely not, thank you. I'll update my tools.
