### ISSUE TITLE
1.0.3 indentation issues

### ISSUE THREAD

**Issue by lfiorini** [APerricone/harbourCodeExtension#80]
Thank you for 1.0.3 now it doesn't break the code but the indentation is not consistent. Is there a way to disable formatting?

**Comment by APerricone** [comment]
I think you have enabled the [Automatically Format Code On File Save](https://linuxpip.org/vscode-format-on-save/) you can disable it for language.

**Comment by lfiorini** [comment]
Sorry, of course "indentation is not consistent" is not enough but I didn't want to bother you with an issue that can be easily fixed disabling formatting. However if you're interested I can provide examples.

**Comment by APerricone** [comment]
Just for curiosity, can you send some example on my mail?. You can find it on my profile
