### ISSUE TITLE
Add version # 

### ISSUE THREAD

**Issue by alexstrickland** [APerricone/harbourCodeExtension#82]
Could I suggest adding a version # to dbg_lib.prg and to the extension so that the extension can gracefully fail if there have been incompatible changes in the protocol and the user is alerted to manually update dbg_lib.prg.

**Comment by APerricone** [comment]
![image](https://user-images.githubusercontent.com/22457168/163914307-e033a845-f3e8-4c96-b274-e91fe7bf8602.png)
The version is visible on the extension page.
I suggest to update the debugger connection file at every version charge.
