### ISSUE TITLE
Debugger does not start on linux

### ISSUE THREAD

**Issue by EricLendvai** [APerricone/harbourCodeExtension#87]
You can use the following to test the extension https://github.com/EricLendvai/Harbour_Samples/tree/main/HelloHarbour
By the way the repo also has support for dev container development.

**Comment by APerricone** [comment]
I will try whit WM, but does not works at all or only the debugger?

**Comment by EricLendvai** [comment]
In debug builds the app simply shuts down with no output.

**Comment by APerricone** [comment]
I tried, **the extension works fine on Ubuntu.**

**Comment by EricLendvai** [comment]
Hello Antonino, version 1.0.7 works again. Probably your fix for issue #87 also fixed this issue.
This was not an "alarmist issue report".
The best way to replicate the original issue was to use the steps described in article 
https://harbour.wiki/index.asp?page=PublicArticles&mode=show&id=221022022831&sig=9123873596
using the HelloHarbour sample. 
I am now developing using the VSCode Dev Extension in a Ubuntu container in Docker.
Your extension is fantastic in that development environment!

**Comment by APerricone** [comment]
> This was not an "alarmist issue report".

When I see "Versions do not work in Ubunutu" I was panic that the extension did not work at all 😊
The big improve was include  [yagisumi/node-win-output-debug-string](https://github.com/yagisumi/node-win-output-debug-string) to show debug output so it is no more necessary use winDbg

**Comment by EricLendvai** [comment]
Sorry that my report created such worry for you. It was not my intention, just wanted to help you out.

Thank you about the big improve about DebugView. I had noticed a change, but did not realize it was your enhancement in the extension. This makes it so much easier for users than to need to run the DebugView application.

I will update the article documenting your extension to reflect this enhancement.

Would it be possible to also make it work with Linux SysLog messages? I think it is also using UDP messages?
Here is the code for HelloHarbour.prg where I use OutputDebugString or syslog.


`#define MAXLOOP 9

Function Main()
local l_loop

DebugView("Starting Hello World")

FOR l_loop := 1 to MAXLOOP
    ?"Hello Harbour " + alltrim(str(l_loop))
    IF l_loop == 4
        AltD()
        ?"Paused Debugger" 
    ENDIF
END

DebugView("Completed Hello World")

RETURN nil
//===========================================================================
function DebugView(par_cMessage)
#ifdef DEBUGVIEW   // The DEBUGVIEW precompiler variable is defined in BuildEXE.bat and BuildEXE.sh
    if hb_osIsWin7()
        DebugViewOrTrace("[Harbour] "+par_cMessage)
    else
        DebugViewOrTrace(par_cMessage)  // No need to prefix with [Harbour], since the SysLog call will also prefix it.
    endif
#endif
return nil
//===========================================================================
#pragma BEGINDUMP
#include "hbapi.h"
#ifdef _WIN32   // Only MS Windows has DebugView
    #include <windows.h>
#else
    #include <syslog.h>
#endif

HB_FUNC( DEBUGVIEWORTRACE )
{
#ifdef _WIN32
   OutputDebugString( hb_parc(1) );  // Using Windows DebugView
#else
    setlogmask(LOG_UPTO (LOG_DEBUG));
    openlog("[Harbour]", LOG_PID | LOG_NDELAY, LOG_LOCAL1);
    syslog(LOG_DEBUG, hb_parc(1));
    closelog();
#endif
}
#pragma ENDDUMP
//===========================================================================`
