### ISSUE TITLE
Add "go to definition" when inside workspace

### ISSUE THREAD

**Issue by ycabral** [APerricone/harbourCodeExtension#9]
Hi, when I try to use the "Go to Definition" or "Peek Definition" feature on macOS while inside a workspace and I get "Definition not found" when I try to use these features. I work on an environment that we use CVS and not git repositories, and since vscode doesn't support CVS repositories I need to create a folder for every new branch I create or work on, so this is why I have to use inside a workspace. Is there anykind of extra config I have to do, or the extension doesn't support workspace feature yet? I think that would be a great improvement, if it doesn't. Thank you, great job with this extension. :)

**Comment by APerricone** [comment]
Hi, I am not sure to understand your problem.
Unfortunately , [the language server protocol does not support multi folder root](https://github.com/Microsoft/language-server-protocol/issues/298).
Actually this extension look inside the inside only the first work space root.
When that issue will be solved I will solve this.

**Comment by APerricone** [comment]
Going deeper, I see that the multi folder is supported from the version 3.6, I will add it to next release.
