### ISSUE TITLE
Quick help for standard procedure/function

### ISSUE THREAD

**Issue by ryzhovalexandr** [APerricone/harbourCodeExtension#92]
There are several doc sites, where I read information about standard functions of Harbour, f.e. 
https://harbour.github.io/doc/
https://harbour.wiki/index.asp?page=PublicHarbourAPIExplorer
It would be great if I can navigate this information in VSCode by hotkey, or tip by mouse

**Comment by APerricone** [comment]
Hello, it is already present, on my configuration is on CTRL+SPACE

**Comment by ryzhovalexandr** [comment]
is it undocumented feature? or I have missed it?
Ctrl + Space for me is working slightly different, it tries to help me choose right function. It useful, but how can I see description of this function and its parameters?
![image](https://user-images.githubusercontent.com/4340982/220473156-5da8c838-2fc6-4c29-ad2a-d468198ca52c.png)

**Comment by ryzhovalexandr** [comment]
I've found what I was looking for. While cursour into the brackets I pressed Ctrl+Shift+Space and see the description
![image](https://user-images.githubusercontent.com/4340982/220777729-4eac3120-e5f0-4fef-bf11-32ec2646d451.png)
