### ISSUE TITLE
Support for custom encoding strings while debugging

### ISSUE THREAD

**Issue by ryzhovalexandr** [APerricone/harbourCodeExtension#93]
I have legacy application, which uses specific coding page - cp866. VSCode is ok with source code - I change encoding for prg files in .workspace file. But when I debug application I see wrong characters in whatch and navigate panels.
It would be great if i can configure encoding in plugin settings.

**Comment by APerricone** [comment]
can you post a screenshot? Did you call hb_cdpSelect ?

**Comment by ryzhovalexandr** [comment]
yes, we call hb_cdpSelect in the beginning
![image](https://user-images.githubusercontent.com/4340982/220477379-b92bf32e-830f-4baa-8c3a-d3801df3a6d5.png)

it's miracle, now it's working, thank you, i think it's not actual now
